
"use strict";
const C={W:640,H:360,WW:2304,WH:1536,PS:155,ES:46,AR:48,QR:280,QD:.8,QS:4,QCD:16,WCD:9,WMAX:3,ECD:13,RCD:35,RD:8,SPAWN:2.0,MAXE:32};
const canvas=document.querySelector("#game"),ctx=canvas.getContext("2d",{alpha:false}),loading=document.querySelector("#loading"),loadingText=document.querySelector("#loadingText");ctx.imageSmoothingEnabled=false;

class Assets{constructor(m){this.m=m;this.i={}}async load(){let n=0,e=Object.entries(this.m);await Promise.all(e.map(([k,s])=>new Promise((ok,fail)=>{let im=new Image;im.onload=()=>{this.i[k]=im;loadingText.textContent=`에셋 불러오는 중… ${++n}/${e.length}`;ok()};im.onerror=()=>fail(Error(`로드 실패: ${s}`));im.src=s})));return this.i}}
class Input{constructor(){this.d=new Set;this.p=new Set;addEventListener("keydown",e=>{let k=e.key.toLowerCase();if(!this.d.has(k))this.p.add(k);this.d.add(k);if(["arrowup","arrowdown","arrowleft","arrowright","a","q","w","e","r","1","2","3"].includes(k))e.preventDefault()});addEventListener("keyup",e=>this.d.delete(e.key.toLowerCase()))}held(k){return this.d.has(k)}tap(k){return this.p.has(k)}end(){this.p.clear()}}
class Camera{constructor(){this.x=0;this.y=0}follow(t,dt){let s=1-Math.exp(-9*dt);this.x+=(t.x-C.W/2-this.x)*s;this.y+=(t.y-C.H/2-this.y)*s;this.x=Math.max(0,Math.min(C.WW-C.W,this.x));this.y=Math.max(0,Math.min(C.WH-C.H,this.y))}screen(x,y){return{x:Math.round(x-this.x),y:Math.round(y-this.y)}}}
class Anim{constructor(i,w,h,n,f,l=true){Object.assign(this,{i,w,h,n,f,l});this.reset()}reset(){this.fr=0;this.t=0;this.done=false}update(dt,speed=1){if(this.done)return;this.t+=dt*speed;while(this.t>=1/this.f){this.t-=1/this.f;if(++this.fr>=this.n){if(this.l)this.fr=0;else{this.fr=this.n-1;this.done=true}}}}draw(c,x,y,s=1,flip=false,a=1){c.save();c.globalAlpha=a;c.translate(Math.round(x),Math.round(y));if(flip)c.scale(-1,1);let W=this.w*s,H=this.h*s;c.drawImage(this.i,this.fr*this.w,0,this.w,this.h,-W/2,-H*.78,W,H);c.restore()}}
class SheetFX{constructor(img,fw,fh,frames,x,y,scale=1,d=.35,flip=false){Object.assign(this,{img,fw,fh,frames,x,y,scale,d,flip});this.life=d}update(dt){this.life-=dt}draw(c,cam){let p=cam.screen(this.x,this.y),progress=1-this.life/this.d,fr=Math.min(this.frames-1,Math.floor(progress*this.frames));c.save();c.translate(p.x,p.y);if(this.flip)c.scale(-1,1);c.globalAlpha=Math.max(0,Math.min(1,this.life/.08));c.drawImage(this.img,fr*this.fw,0,this.fw,this.fh,-this.fw*this.scale/2,-this.fh*this.scale/2,this.fw*this.scale,this.fh*this.scale);c.restore()}}
class RingFX{constructor(type,x,y,r,d=.25){Object.assign(this,{type,x,y,r,d});this.life=d}update(dt){this.life-=dt}draw(c,cam){let p=cam.screen(this.x,this.y),t=Math.max(0,this.life/this.d);c.save();c.globalAlpha=t;c.strokeStyle=this.type==="attack"?"#f5e9b8":"#5ebcff";c.lineWidth=2;c.beginPath();c.arc(p.x,p.y,this.r*(1+(1-t)*.15),0,Math.PI*2);c.stroke();c.restore()}}

class Enemy{
constructor(img,x,y,id,l=1){this.x=x;this.y=y;this.id=id;this.level=l;this.max=4+Math.floor(l*.8);this.hp=this.max;this.dead=false;this.rewarded=false;this.flash=0;this.touch=0;this.anim=new Anim(img,32,32,4,6)}
damage(n,fx,px,py){if(this.dead)return false;this.hp-=n;this.flash=.1;let dx=this.x-px,dy=this.y-py,d=Math.hypot(dx,dy)||1;this.x+=dx/d*8;this.y+=dy/d*8;if(this.hp<=0)this.dead=true;return true}
update(dt,p){if(this.dead)return;this.anim.update(dt);this.flash=Math.max(0,this.flash-dt);this.touch=Math.max(0,this.touch-dt);let dx=p.x-this.x,dy=p.y-this.y,d=Math.hypot(dx,dy)||1;if(!p.q.on){this.x+=dx/d*(C.ES+this.level*.5)*dt;this.y+=dy/d*(C.ES+this.level*.5)*dt}if(d<23&&this.touch<=0&&!p.q.on){p.hurt(8+Math.floor(this.level/4));this.touch=.75}}
draw(c,cam){if(this.dead)return;let p=cam.screen(this.x,this.y);c.fillStyle="rgba(0,0,0,.25)";c.beginPath();c.ellipse(p.x,p.y+3,10,4,0,0,Math.PI*2);c.fill();this.anim.draw(c,p.x,p.y,1.25,false,this.flash>0?.45:1);c.fillStyle="#25120f";c.fillRect(p.x-13,p.y-22,26,3);c.fillStyle="#d95b45";c.fillRect(p.x-13,p.y-22,26*this.hp/this.max,3)}
}

class Player{
constructor(i){this.i=i;this.x=C.WW/2;this.y=C.WH/2;this.level=1;this.xp=0;this.need=35;this.gold=0;this.maxHp=100;this.hp=100;this.atk=1;this.left=false;this.state="idle";this.hit=false;this.inv=0;this.choices=[];this.q={open:false,on:false,t:0,next:0,count:0,cd:0,lv:0,targets:[]};this.w={open:false,cd:0,lv:0};this.e={open:false,cd:0,lv:0,on:false,t:0};this.r={open:false,cd:0,lv:0,on:false,t:0};this.med=false;this.medT=0;this.a={idle:new Anim(i.idle,96,96,10,8),run:new Anim(i.run,96,96,16,15),attack:new Anim(i.attack,96,96,7,15,false)}}
hurt(n){if(this.inv>0||this.q.on)return;this.hp=Math.max(0,this.hp-n);this.inv=.35}
reward(g,x){this.gold+=g;this.xp+=x;if(this.xp>=this.need){this.xp-=this.need;this.level++;this.need=Math.floor(this.need*1.32+8);this.makeChoices()}}
makeChoices(){let p=[];if(!this.q.open)p.push({id:"qu",n:"알파 해금",d:"Q 사용 가능"});else p.push({id:"q",n:"알파 강화",d:"피해/사거리 증가"});if(!this.w.open)p.push({id:"wu",n:"명상 해금",d:"W 사용 가능"});else p.push({id:"w",n:"명상 강화",d:"회복량 증가"});if(!this.e.open)p.push({id:"eu",n:"우주류 해금",d:"E 사용 가능"});else p.push({id:"e",n:"우주류 강화",d:"추가 피해 증가"});if(!this.r.open)p.push({id:"ru",n:"최후의 전사 해금",d:"R 궁극기"});else p.push({id:"r",n:"궁극기 강화",d:"지속시간 증가"});p.push({id:"hp",n:"체력 단련",d:"최대 체력 +20"},{id:"atk",n:"검술 숙련",d:"평타 피해 +1"});p.sort(()=>Math.random()-.5);this.choices=p.slice(0,3)}
choose(i){let c=this.choices[i];if(!c)return;let s=this[c.id[0]];if(c.id==="qu"){this.q.open=true;this.q.lv=1}else if(c.id==="wu"){this.w.open=true;this.w.lv=1}else if(c.id==="eu"){this.e.open=true;this.e.lv=1}else if(c.id==="ru"){this.r.open=true;this.r.lv=1}else if(["q","w","e","r"].includes(c.id))this[c.id].lv++;else if(c.id==="hp"){this.maxHp+=20;this.hp=Math.min(this.maxHp,this.hp+35)}else if(c.id==="atk")this.atk++;this.choices=[]}
cancel(){this.state="idle";this.a.attack.reset();this.hit=false}
near(es,r){return es.filter(e=>!e.dead&&Math.hypot(e.x-this.x,e.y-this.y)<=r).sort((a,b)=>Math.hypot(a.x-this.x,a.y-this.y)-Math.hypot(b.x-this.x,b.y-this.y))}
startQ(es){if(!this.q.open||this.q.cd>0||this.q.on||this.med)return;let r=C.QR+20*(this.q.lv-1),t=this.near(es,r);if(!t.length)return;this.cancel();this.q={open:true,on:true,t:0,next:0,count:0,cd:C.QCD,lv:this.q.lv,targets:t}}
strikeQ(es,fx){let r=C.QR+20*(this.q.lv-1),ts=this.near(es,r);if(!ts.length)return;let t=ts[this.q.count%ts.length];let a=Math.atan2(t.y-this.y,t.x-this.x);this.x=t.x-Math.cos(a)*18;this.y=t.y-Math.sin(a)*18;t.damage(1+this.q.lv,fx,this.x,this.y);fx.push(new SheetFX(this.i.alpha,32,32,4,t.x,t.y,1.6,.28,this.left));this.q.count++}
startW(){if(!this.w.open||this.w.cd>0||this.q.on)return;this.cancel();this.med=true;this.medT=0;this.w.cd=C.WCD}
castE(){if(!this.e.open||this.e.cd>0||this.q.on||this.med)return;this.cancel();this.e.cd=C.ECD;this.e.on=true;this.e.t=5}
castR(fx){if(!this.r.open||this.r.cd>0||this.q.on)return;this.cancel();this.r.cd=C.RCD;this.r.on=true;this.r.t=C.RD+this.r.lv;fx.push(new SheetFX(this.i.boost,53,35,8,this.x,this.y,1.45,.55,false))}
update(dt,input,es,fx){
this.inv=Math.max(0,this.inv-dt);for(let s of [this.q,this.w,this.e,this.r])s.cd=Math.max(0,s.cd-dt);if(this.e.on&&(this.e.t-=dt)<=0)this.e.on=false;if(this.r.on&&(this.r.t-=dt)<=0)this.r.on=false;
if(input.tap("q"))this.startQ(es);if(input.tap("w"))this.startW();if(input.tap("e"))this.castE();if(input.tap("r"))this.castR(fx);
if(this.q.on){this.q.t+=dt;while(this.q.count<C.QS&&this.q.t>=this.q.next){this.strikeQ(es,fx);this.q.next+=C.QD/C.QS}if(this.q.t>=C.QD){this.q.on=false;this.state="idle"}return}
if(this.med){this.medT+=dt;this.hp=Math.min(this.maxHp,this.hp+(8+5*this.w.lv)*dt);if(this.medT>=C.WMAX||input.held("arrowup")||input.held("arrowdown")||input.held("arrowleft")||input.held("arrowright")||input.tap("a")||input.tap("q")||input.tap("e")||input.tap("r")){this.med=false;this.medT=0}return}
if(input.tap("a")){this.state="attack";this.a.attack.reset();this.hit=false}
let aspd=this.r.on?1.65:1;
if(this.state==="attack"&&!this.a.attack.done){this.a.attack.update(dt,aspd);if(!this.hit&&this.a.attack.fr>=3){this.hit=true;let range=C.AR+(this.r.on?22:0),hits=0;fx.push(new RingFX("attack",this.x,this.y,range,.2));for(let e of es)if(!e.dead&&Math.hypot(e.x-this.x,e.y-this.y)<=range){let dmg=this.atk+(this.e.on?(2+this.e.lv):0);if(e.damage(dmg,fx,this.x,this.y))hits++}if(hits)this.q.cd=Math.max(0,this.q.cd-2*hits)}if(this.a.attack.done)this.state="idle";return}
let dx=0,dy=0;if(input.held("arrowleft"))dx--;if(input.held("arrowright"))dx++;if(input.held("arrowup"))dy--;if(input.held("arrowdown"))dy++;if(dx||dy){let l=Math.hypot(dx,dy);dx/=l;dy/=l;let sp=C.PS*(this.r.on?1.45:1);this.x+=dx*sp*dt;this.y+=dy*sp*dt;if(dx<0)this.left=true;if(dx>0)this.left=false;this.state="run"}else this.state="idle";this.x=Math.max(35,Math.min(C.WW-35,this.x));this.y=Math.max(35,Math.min(C.WH-35,this.y));this.a[this.state].update(dt)}
aura(c,cam,col,r){let p=cam.screen(this.x,this.y),u=1+Math.sin(performance.now()/120)*.12;c.save();c.globalCompositeOperation="screen";c.globalAlpha=.2;c.fillStyle=col;c.beginPath();c.ellipse(p.x,p.y-7,r*u,r*1.35*u,0,0,Math.PI*2);c.fill();c.globalAlpha=.8;c.strokeStyle=col;c.lineWidth=2;c.beginPath();c.arc(p.x,p.y-8,r*.8*u,0,Math.PI*2);c.stroke();c.restore()}
draw(c,cam){if(this.q.on)return;let p=cam.screen(this.x,this.y);if(this.med)this.aura(c,cam,"#6bff83",30);if(this.r.on)this.aura(c,cam,"#ffd86b",36);c.fillStyle="rgba(0,0,0,.28)";c.beginPath();c.ellipse(p.x,p.y+4,18,7,0,0,Math.PI*2);c.fill();this.a[this.state==="attack"?"attack":this.state].draw(c,p.x,p.y,1.35,this.left,this.inv>0?.55:1);if(this.e.on){c.save();c.globalCompositeOperation="screen";c.strokeStyle="#69bfff";c.lineWidth=3;c.shadowColor="#3c8cff";c.shadowBlur=8;c.beginPath();c.moveTo(p.x+(this.left?-17:17),p.y-30);c.lineTo(p.x+(this.left?-35:35),p.y+2);c.stroke();c.restore()}}
}

class World{constructor(i){this.i=i;this.p=[];let r=this.rand(80231),cx=C.WW/2,cy=C.WH/2;for(let n=0;n<115;n++){let x=50+r()*(C.WW-100),y=50+r()*(C.WH-100);if(Math.hypot(x-cx,y-cy)<170)continue;this.p.push({t:r()<.42?"c":"r",x,y,f:Math.floor(r()*4)})}this.p.sort((a,b)=>a.y-b.y)}rand(s){return()=>((s=Math.imul(1664525,s)+1013904223>>>0)/4294967296)}ground(c,cam){let sx=Math.floor(cam.x/16)*16,sy=Math.floor(cam.y/16)*16;for(let y=sy;y<cam.y+C.H+16;y+=16)for(let x=sx;x<cam.x+C.W+16;x+=16){let p=cam.screen(x,y);c.drawImage(this.i.grass,p.x,p.y,16,16);let h=((x*31+y*17)>>4)&31;if(h===0)c.drawImage(this.i.plains,0,64,16,16,p.x,p.y,16,16);if(h===7)c.drawImage(this.i.decor,16,0,16,16,p.x,p.y,16,16)}}prop(c,cam,o){let p=cam.screen(o.x,o.y);if(p.x<-40||p.y<-40||p.x>680||p.y>400)return;o.t==="c"?c.drawImage(this.i.chest,o.f*16,0,16,16,p.x-8,p.y-14,16,16):c.drawImage(this.i.rock,0,0,16,16,p.x-8,p.y-13,16,16)}}

class Game{
constructor(i){this.i=i;this.input=new Input;this.cam=new Camera;this.world=new World(i);this.p=new Player(i);this.es=[];this.fx=[];this.sp=0;this.id=0;this.last=performance.now();for(let n=0;n<8;n++)this.spawn()}
spawn(){if(this.es.filter(e=>!e.dead).length>=C.MAXE)return;let a=Math.random()*Math.PI*2,d=230+Math.random()*170,x=Math.max(40,Math.min(C.WW-40,this.p.x+Math.cos(a)*d)),y=Math.max(40,Math.min(C.WH-40,this.p.y+Math.sin(a)*d));this.es.push(new Enemy(this.i.slime,x,y,this.id++,this.p.level))}
reset(){this.p=new Player(this.i);this.es=[];this.fx=[];this.sp=0;for(let n=0;n<8;n++)this.spawn()}
update(dt){if(this.p.choices.length){if(this.input.tap("1"))this.p.choose(0);if(this.input.tap("2"))this.p.choose(1);if(this.input.tap("3"))this.p.choose(2);return}this.sp+=dt;if(this.sp>=C.SPAWN){this.sp=0;this.spawn()}this.p.update(dt,this.input,this.es,this.fx);for(let e of this.es)e.update(dt,this.p);for(let f of this.fx)f.update(dt);this.fx=this.fx.filter(f=>f.life>0);for(let e of this.es)if(e.dead&&!e.rewarded){e.rewarded=true;this.p.reward(3+Math.floor(e.level*.5),8+e.level*2)}if(this.es.length>90)this.es=this.es.filter(e=>!e.dead);this.cam.follow(this.p,dt);if(this.p.hp<=0)this.reset()}
draw(){this.world.ground(ctx,this.cam);let l=[];for(let o of this.world.p)l.push({y:o.y,d:()=>this.world.prop(ctx,this.cam,o)});for(let e of this.es)if(!e.dead)l.push({y:e.y,d:()=>e.draw(ctx,this.cam)});if(!this.p.q.on)l.push({y:this.p.y,d:()=>this.p.draw(ctx,this.cam)});l.sort((a,b)=>a.y-b.y);for(let x of l)x.d();for(let f of this.fx)f.draw(ctx,this.cam);this.hud();if(this.p.choices.length)this.menu()}
bar(x,y,w,h,r,b,f){ctx.fillStyle=b;ctx.fillRect(x,y,w,h);ctx.fillStyle=f;ctx.fillRect(x,y,w*Math.max(0,Math.min(1,r)),h);ctx.strokeStyle="rgba(255,255,255,.35)";ctx.strokeRect(x+.5,y+.5,w-1,h-1)}
skillBox(x,key,s,baseCd){let ready=s.open&&s.cd<=0;ctx.fillStyle=s.open?"rgba(15,25,20,.9)":"rgba(10,10,10,.88)";ctx.fillRect(x,307,48,43);ctx.strokeStyle=ready?"#ddebba":"#536056";ctx.strokeRect(x+.5,307.5,47,42);ctx.fillStyle=s.open?"#eef5d8":"#777";ctx.font="bold 12px monospace";ctx.fillText(key,x+6,321);ctx.font="8px monospace";ctx.fillText(s.open?(s.cd>0?s.cd.toFixed(1):"READY"):"LOCK",x+6,342);if(s.open&&s.cd>0){let ratio=Math.min(1,s.cd/baseCd);ctx.fillStyle="rgba(10,15,20,.62)";ctx.fillRect(x,307,48,43*ratio)}}
hud(){let p=this.p;ctx.fillStyle="rgba(8,14,9,.88)";ctx.fillRect(116,286,408,70);ctx.strokeStyle="rgba(210,235,182,.48)";ctx.strokeRect(116.5,286.5,407,69);this.bar(128,294,150,8,p.hp/p.maxHp,"#321718","#d45f57");this.bar(128,306,150,6,p.xp/p.need,"#182433","#5ca8e6");ctx.fillStyle="#eaf3d5";ctx.font="8px monospace";ctx.fillText(`LV.${p.level}  HP ${Math.ceil(p.hp)}/${p.maxHp}  XP ${p.xp}/${p.need}  G ${p.gold}`,128,326);this.skillBox(292,"Q",p.q,C.QCD);this.skillBox(344,"W",p.w,C.WCD);this.skillBox(396,"E",p.e,C.ECD);this.skillBox(448,"R",p.r,C.RCD);if(p.med){ctx.fillStyle="#8dff9f";ctx.fillText(`명상 ${Math.max(0,C.WMAX-p.medT).toFixed(1)}초`,128,342)}}
menu(){let a=this.p.choices;ctx.fillStyle="rgba(3,6,5,.84)";ctx.fillRect(0,0,C.W,C.H);ctx.fillStyle="#eef5d8";ctx.font="bold 20px monospace";ctx.textAlign="center";ctx.fillText(`LEVEL ${this.p.level}`,C.W/2,72);ctx.font="10px monospace";ctx.fillText("1 / 2 / 3 중 하나를 선택하세요",C.W/2,94);a.forEach((o,i)=>{let x=82+i*164,y=125,w=148,h=112;ctx.fillStyle="#101a12";ctx.fillRect(x,y,w,h);ctx.strokeStyle="#8fb66f";ctx.strokeRect(x+.5,y+.5,w-1,h-1);ctx.font="bold 14px monospace";ctx.fillText(String(i+1),x+w/2,y+24);ctx.font="bold 10px monospace";ctx.fillText(o.n,x+w/2,y+52);ctx.font="9px monospace";ctx.fillStyle="#a9c59a";ctx.fillText(o.d,x+w/2,y+78)});ctx.textAlign="left"}
loop=(t)=>{let dt=Math.min((t-this.last)/1000,.05);this.last=t;this.update(dt);this.draw();this.input.end();requestAnimationFrame(this.loop)}
start(){loading.classList.add("hidden");requestAnimationFrame(this.loop)}
}
const manifest={idle:"assets/player/idle.png",run:"assets/player/run.png",attack:"assets/player/attack.png",slime:"assets/enemies/slime.png",grass:"assets/tiles/grass.png",plains:"assets/tiles/plains.png",decor:"assets/tiles/decor.png",chest:"assets/objects/chest.png",rock:"assets/objects/rock.png",alpha:"assets/fx/alpha_slash.png",boost:"assets/fx/ultimate_boost.png"};
(async()=>{try{new Game(await new Assets(manifest).load()).start()}catch(e){console.error(e);loadingText.textContent=e.message}})();
