
"use strict";
const C={W:640,H:360,WW:2304,WH:1536,PS:155,AR:48,QCD:16,WCD:9,ECD:13,RCD:35,SPAWN:1.8,MAXE:36};
const canvas=document.querySelector("#game"),ctx=canvas.getContext("2d",{alpha:false}),loading=document.querySelector("#loading"),loadingText=document.querySelector("#loadingText");ctx.imageSmoothingEnabled=false;
class Assets{constructor(m){this.m=m;this.i={}}async load(){let n=0,e=Object.entries(this.m);await Promise.all(e.map(([k,s])=>new Promise(o=>{let im=new Image,done=false;const finish=ok=>{if(done)return;done=true;if(ok)this.i[k]=im;else{let cv=document.createElement("canvas");cv.width=cv.height=2;this.i[k]=cv;console.error("에셋 로드 실패:",s)}loadingText.textContent=`에셋 ${++n}/${e.length}`;o()};im.onload=()=>finish(true);im.onerror=()=>finish(false);setTimeout(()=>finish(false),5000);im.src=s})));return this.i}}
class AudioSys{constructor(){this.s={};this.ready=false}add(k,src,loop=false,v=.5){let a=new Audio(src);a.loop=loop;a.volume=v;this.s[k]=a}unlock(){if(this.ready)return;this.ready=true;this.s.bgm.play().catch(()=>{})}play(k){this.unlock();let a=this.s[k];if(!a)return;let b=a.cloneNode();b.volume=a.volume;b.play().catch(()=>{})}}
class Input{constructor(audio){this.d=new Set;this.p=new Set;addEventListener("keydown",e=>{audio.unlock();let k=e.key.toLowerCase();if(!this.d.has(k))this.p.add(k);this.d.add(k);if(["arrowup","arrowdown","arrowleft","arrowright","a","q","w","e","r","f","1","2","3"].includes(k))e.preventDefault()});addEventListener("keyup",e=>this.d.delete(e.key.toLowerCase()));addEventListener("pointerdown",()=>audio.unlock())}held(k){return this.d.has(k)}tap(k){return this.p.has(k)}end(){this.p.clear()}}
class Cam{constructor(){this.x=0;this.y=0}follow(p,dt){let s=1-Math.exp(-9*dt);this.x+=(p.x-C.W/2-this.x)*s;this.y+=(p.y-C.H/2-this.y)*s;this.x=Math.max(0,Math.min(C.WW-C.W,this.x));this.y=Math.max(0,Math.min(C.WH-C.H,this.y))}s(x,y){return{x:Math.round(x-this.x),y:Math.round(y-this.y)}}}
class Anim{constructor(img,fw,fh,n,f){Object.assign(this,{img,fw,fh,n,f});this.fr=0;this.t=0}u(dt,sp=1){this.t+=dt*sp;while(this.t>=1/this.f){this.t-=1/this.f;this.fr=(this.fr+1)%this.n}}d(c,x,y,sc=1,flip=false){c.save();c.translate(x,y);if(flip)c.scale(-1,1);c.drawImage(this.img,this.fr*this.fw,0,this.fw,this.fh,-this.fw*sc/2,-this.fh*sc*.75,this.fw*sc,this.fh*sc);c.restore()}}
class FX{constructor(img,fw,fh,n,x,y,sc=.9,d=.3,flip=false){Object.assign(this,{img,fw,fh,n,x,y,sc,d,flip});this.life=d}u(dt){this.life-=dt}d0(c,cam){let p=cam.s(this.x,this.y),fr=Math.min(this.n-1,Math.floor((1-this.life/this.d)*this.n));c.save();c.translate(p.x,p.y);if(this.flip)c.scale(-1,1);c.globalAlpha=Math.max(0,Math.min(1,this.life/.06));c.drawImage(this.img,fr*this.fw,0,this.fw,this.fh,-this.fw*this.sc/2,-this.fh*this.sc/2,this.fw*this.sc,this.fh*this.sc);c.restore()}}
class Coin{constructor(x,y){this.x=x;this.y=y;this.t=Math.random()*6.28;this.dead=false}u(dt,p,a){this.t+=dt*4;if(Math.hypot(p.x-this.x,p.y-this.y)<20){this.dead=true;p.gold++;a.play("coin")}}d(c,cam){let p=cam.s(this.x,this.y),b=Math.sin(this.t)*2;c.fillStyle="#f7cf4a";c.beginPath();c.arc(p.x,p.y-5+b,3.5,0,Math.PI*2);c.fill();c.strokeStyle="#9e6d18";c.stroke()}}
class Enemy{constructor(type,img,x,y,level=1){this.type=type;this.x=x;this.y=y;this.dead=false;this.rewarded=false;this.hit=0;let cfg={slime:[32,32,4,6,4,45],archer:[192,192,4,7,7,38],lancer:[320,320,6,8,11,52],boss:[120,80,10,8,45,36]}[type];[this.fw,this.fh,this.frames,this.fps,this.max,this.speed]=cfg;this.hp=this.max+level;this.max=this.hp;this.anim=new Anim(img,this.fw,this.fh,this.frames,this.fps);this.touch=0}
damage(n){if(this.dead)return false;this.hp-=n;this.hit=.1;if(this.hp<=0)this.dead=true;return true}
u(dt,p){if(this.dead)return;this.anim.u(dt);this.hit=Math.max(0,this.hit-dt);this.touch=Math.max(0,this.touch-dt);let dx=p.x-this.x,dy=p.y-this.y,d=Math.hypot(dx,dy)||1;if(this.type==="archer"&&d<150){this.x-=dx/d*this.speed*.35*dt;this.y-=dy/d*this.speed*.35*dt}else{this.x+=dx/d*this.speed*dt;this.y+=dy/d*this.speed*dt}let hitRange=this.type==="boss"?34:22;if(d<hitRange&&this.touch<=0&&!p.q.on){p.hurt(this.type==="boss"?18:this.type==="lancer"?11:8);this.touch=this.type==="boss"?.55:.8}}
d(c,cam){if(this.dead)return;let p=cam.s(this.x,this.y),sc=this.type==="boss"?1.05:this.type==="slime"?1.25:.28;c.save();c.globalAlpha=this.hit>0?.45:1;this.anim.d(c,p.x,p.y,sc,false);c.restore();let w=this.type==="boss"?70:28;c.fillStyle="#25120f";c.fillRect(p.x-w/2,p.y-(this.type==="boss"?47:24),w,4);c.fillStyle=this.type==="boss"?"#b24cf0":"#dc5d48";c.fillRect(p.x-w/2,p.y-(this.type==="boss"?47:24),w*this.hp/this.max,4)}
}
class Player{constructor(i,a){this.i=i;this.audio=a;this.x=C.WW/2;this.y=C.WH/2;this.hp=100;this.maxHp=100;this.gold=0;this.xp=0;this.need=35;this.level=1;this.atk=1;this.left=false;this.attackT=0;this.attackDone=false;this.inv=0;this.med=false;this.medT=0;this.q={open:false,cd:0,on:false,t:0,count:0};this.w={open:false,cd:0};this.e={open:false,cd:0,on:false,t:0};this.r={open:false,cd:0,on:false,t:0};this.choices=[];this.idle=new Anim(i.idle,96,96,10,8);this.run=new Anim(i.run,96,96,16,15);this.att=new Anim(i.attack,96,96,7,15)}
hurt(n){if(this.inv>0||this.q.on)return;this.hp=Math.max(0,this.hp-n);this.inv=.35}
reward(g,x){this.gold+=g;this.xp+=x;if(this.xp>=this.need){this.xp-=this.need;this.level++;this.need=Math.floor(this.need*1.3+8);this.makeChoices();this.audio.play("level")}}
makeChoices(){let p=[];for(let [k,n] of [["q","알파 스트라이크"],["w","명상"],["e","우주류 검술"],["r","최후의 전사"]])p.push({id:k,n:(this[k].open?"강화: ":"해금: ")+n});p.push({id:"hp",n:"체력 +20"},{id:"atk",n:"평타 피해 +1"});p.sort(()=>Math.random()-.5);this.choices=p.slice(0,3)}
choose(n){let c=this.choices[n];if(!c)return;if("qwer".includes(c.id))this[c.id].open=true;else if(c.id==="hp"){this.maxHp+=20;this.hp+=20}else this.atk++;this.choices=[]}
basic(es,fx){let r=C.AR+(this.r.on?22:0);this.attackT=.33/(this.r.on?1.6:1);this.attackDone=false;this.audio.play("attack");for(let e of es)if(!e.dead&&Math.hypot(e.x-this.x,e.y-this.y)<=r){e.damage(this.atk+(this.e.on?3:0));this.q.cd=Math.max(0,this.q.cd-2)}}
startQ(es,fx){if(!this.q.open||this.q.cd>0)return;let ts=es.filter(e=>!e.dead&&Math.hypot(e.x-this.x,e.y-this.y)<290);if(!ts.length)return;this.q.cd=16;this.q.on=true;this.q.t=0;this.q.count=0;this.audio.play("alpha")}
u(dt,input,es,fx){
this.inv=Math.max(0,this.inv-dt);for(let k of "qwer")this[k].cd=Math.max(0,this[k].cd-dt);if(this.e.on&&(this.e.t-=dt)<=0)this.e.on=false;if(this.r.on&&(this.r.t-=dt)<=0)this.r.on=false;
if(input.tap("a"))this.basic(es,fx);if(input.tap("q"))this.startQ(es,fx);if(input.tap("w")&&this.w.open&&this.w.cd<=0){this.w.cd=9;this.med=true;this.medT=0;this.audio.play("med")}if(input.tap("e")&&this.e.open&&this.e.cd<=0){this.e.cd=13;this.e.on=true;this.e.t=5;fx.push(new FX(this.i.circle,16,32,8,this.x,this.y,2.2,.5));}if(input.tap("r")&&this.r.open&&this.r.cd<=0){this.r.cd=35;this.r.on=true;this.r.t=9;this.audio.play("ult");fx.push(new FX(this.i.aura,64,64,8,this.x,this.y,1.4,.7))}
if(this.q.on){this.q.t+=dt;while(this.q.count<4&&this.q.t>=this.q.count*.2){let ts=es.filter(e=>!e.dead&&Math.hypot(e.x-this.x,e.y-this.y)<290);if(ts.length){let t=ts[this.q.count%ts.length],ang=Math.atan2(t.y-this.y,t.x-this.x);this.x=t.x-Math.cos(ang)*18;this.y=t.y-Math.sin(ang)*18;t.damage(2);let imgs=[this.i.a1,this.i.a2,this.i.a3,this.i.a4];fx.push(new FX(imgs[this.q.count%4],32,32,4,t.x,t.y,1.7,.28,this.q.count%2===1));}this.q.count++}if(this.q.t>=.8)this.q.on=false;return}
if(this.med){this.medT+=dt;this.hp=Math.min(this.maxHp,this.hp+14*dt);if(this.medT>=3||input.held("arrowup")||input.held("arrowdown")||input.held("arrowleft")||input.held("arrowright")||input.tap("a"))this.med=false}
let dx=0,dy=0;if(input.held("arrowleft"))dx--;if(input.held("arrowright"))dx++;if(input.held("arrowup"))dy--;if(input.held("arrowdown"))dy++;let moving=dx||dy;if(moving&&!this.med){let l=Math.hypot(dx,dy),sp=C.PS*(this.r.on?1.45:1);dx/=l;dy/=l;this.x+=dx*sp*dt;this.y+=dy*sp*dt;if(dx<0)this.left=true;if(dx>0)this.left=false;this.run.u(dt)}else this.idle.u(dt);if(this.attackT>0)this.attackT-=dt;this.x=Math.max(35,Math.min(C.WW-35,this.x));this.y=Math.max(35,Math.min(C.WH-35,this.y))}
d(c,cam){if(this.q.on)return;let p=cam.s(this.x,this.y);if(this.r.on){c.globalAlpha=.35;c.drawImage(this.i.spirit,p.x-48,p.y-58,96,96);c.globalAlpha=1}if(this.med){c.strokeStyle="#71ff83";c.lineWidth=3;c.beginPath();c.arc(p.x,p.y-8,28+Math.sin(performance.now()/120)*3,0,Math.PI*2);c.stroke()}let an=this.attackT>0?this.att:(this.run);an.d(c,p.x,p.y,1.35,this.left);if(this.e.on){c.strokeStyle="#68c6ff";c.lineWidth=4;c.shadowColor="#3d8cff";c.shadowBlur=8;c.beginPath();c.moveTo(p.x+(this.left?-14:14),p.y-31);c.lineTo(p.x+(this.left?-34:34),p.y+1);c.stroke();c.shadowBlur=0}}
}
class Game{
constructor(i){this.i=i;this.audio=new AudioSys;this.audio.add("bgm","assets/audio/bgm.ogg",true,.32);this.audio.add("attack","assets/audio/attack.wav",false,.55);this.audio.add("alpha","assets/audio/alpha.wav",false,.65);this.audio.add("med","assets/audio/meditate.wav",false,.55);this.audio.add("ult","assets/audio/ultimate.wav",false,.7);this.audio.add("level","assets/audio/levelup.wav",false,.6);this.audio.add("coin","assets/audio/coin.wav",false,.35);this.input=new Input(this.audio);this.cam=new Cam;this.p=new Player(i,this.audio);this.es=[];this.fx=[];this.coins=[];this.bed={x:C.WW/2+120,y:C.WH/2+60};this.shop=false;this.spawnT=0;this.kills=0;this.last=performance.now();for(let n=0;n<8;n++)this.spawn();for(let n=0;n<24;n++)this.coins.push(new Coin(100+Math.random()*(C.WW-200),100+Math.random()*(C.WH-200)))}
spawn(){if(this.es.filter(e=>!e.dead).length>=C.MAXE)return;let type=Math.random()<.5?"slime":Math.random()<.55?"archer":"lancer";if(this.kills>0&&this.kills%15===0&&!this.es.some(e=>!e.dead&&e.type==="boss"))type="boss";let a=Math.random()*6.28,d=230+Math.random()*170,x=Math.max(40,Math.min(C.WW-40,this.p.x+Math.cos(a)*d)),y=Math.max(40,Math.min(C.WH-40,this.p.y+Math.sin(a)*d));this.es.push(new Enemy(type,this.i[type],x,y,this.p.level))}
u(dt){if(this.p.choices.length){if(this.input.tap("1"))this.p.choose(0);if(this.input.tap("2"))this.p.choose(1);if(this.input.tap("3"))this.p.choose(2);return}if(this.shop){if(this.input.tap("f"))this.shop=false;return}if(this.input.tap("f")&&Math.hypot(this.p.x-this.bed.x,this.p.y-this.bed.y)<55){this.shop=true;return}this.spawnT+=dt;if(this.spawnT>C.SPAWN){this.spawnT=0;this.spawn()}this.p.u(dt,this.input,this.es,this.fx);for(let e of this.es)e.u(dt,this.p);for(let f of this.fx)f.u(dt);for(let c of this.coins)c.u(dt,this.p,this.audio);this.fx=this.fx.filter(f=>f.life>0);this.coins=this.coins.filter(c=>!c.dead);for(let e of this.es)if(e.dead&&!e.rewarded){e.rewarded=true;this.kills++;this.p.reward(e.type==="boss"?30:e.type==="lancer"?7:5,e.type==="boss"?35:10);if(Math.random()<.7)this.coins.push(new Coin(e.x,e.y))}this.cam.follow(this.p,dt);if(this.p.hp<=0)location.reload()}
draw(){let sx=Math.floor(this.cam.x/16)*16,sy=Math.floor(this.cam.y/16)*16;for(let y=sy;y<this.cam.y+C.H+16;y+=16)for(let x=sx;x<this.cam.x+C.W+16;x+=16){let p=this.cam.s(x,y);ctx.drawImage(this.i.grass,p.x,p.y,16,16)}for(let c of this.coins)c.d(ctx,this.cam);let bp=this.cam.s(this.bed.x,this.bed.y);ctx.drawImage(this.i.bed,0,0,64,52,bp.x-32,bp.y-42,64,52);if(Math.hypot(this.p.x-this.bed.x,this.p.y-this.bed.y)<55){ctx.fillStyle="#fff";ctx.font="9px monospace";ctx.fillText("F 상점",bp.x-18,bp.y-50)}let list=[...this.es.filter(e=>!e.dead).map(e=>({y:e.y,d:()=>e.d(ctx,this.cam)})),{y:this.p.y,d:()=>this.p.d(ctx,this.cam)}];list.sort((a,b)=>a.y-b.y);for(let o of list)o.d();for(let f of this.fx)f.d0(ctx,this.cam);this.hud();if(this.shop)this.shopUI();if(this.p.choices.length)this.levelUI()}
skill(x,key,s,img,cd){ctx.fillStyle="#111913";ctx.fillRect(x,309,42,42);ctx.drawImage(img,x+3,312,36,36);if(!s.open){ctx.fillStyle="rgba(0,0,0,.78)";ctx.fillRect(x,309,42,42)}else if(s.cd>0){ctx.fillStyle="rgba(0,0,0,.62)";ctx.fillRect(x,309,42,42*Math.min(1,s.cd/cd));ctx.fillStyle="#fff";ctx.font="9px monospace";ctx.fillText(s.cd.toFixed(1),x+8,334)}ctx.strokeStyle="#b7c99e";ctx.strokeRect(x+.5,309.5,41,41);ctx.fillStyle="#fff";ctx.font="bold 9px monospace";ctx.fillText(key,x+3,319)}
hud(){ctx.fillStyle="rgba(8,14,9,.9)";ctx.fillRect(112,286,416,70);ctx.drawImage(this.i.barBase,122,290,174,35);ctx.drawImage(this.i.barFill,128,298,Math.floor(156*this.p.hp/this.p.maxHp),12);ctx.fillStyle="#fff";ctx.font="8px monospace";ctx.fillText(`HP ${Math.ceil(this.p.hp)}/${this.p.maxHp}`,134,307);ctx.fillText(`LV ${this.p.level}  XP ${this.p.xp}/${this.p.need}  G ${this.p.gold}`,128,330);this.skill(310,"Q",this.p.q,this.i.sq,16);this.skill(354,"W",this.p.w,this.i.sw,9);this.skill(398,"E",this.p.e,this.i.se,13);this.skill(442,"R",this.p.r,this.i.sr,35)}
shopUI(){ctx.fillStyle="rgba(3,6,5,.86)";ctx.fillRect(0,0,C.W,C.H);ctx.fillStyle="#e8efd0";ctx.font="bold 18px monospace";ctx.textAlign="center";ctx.fillText("침대 상점",C.W/2,92);ctx.font="10px monospace";ctx.fillText("아이템 입고 준비 중",C.W/2,120);ctx.fillText(`보유 골드: ${this.p.gold}`,C.W/2,145);ctx.fillText("F 키로 닫기",C.W/2,210);ctx.textAlign="left"}
levelUI(){ctx.fillStyle="rgba(3,6,5,.86)";ctx.fillRect(0,0,C.W,C.H);ctx.fillStyle="#fff";ctx.font="bold 18px monospace";ctx.textAlign="center";ctx.fillText(`LEVEL ${this.p.level}`,320,80);this.p.choices.forEach((o,i)=>{let x=95+i*155;ctx.fillStyle="#132017";ctx.fillRect(x,125,140,100);ctx.strokeStyle="#afca8b";ctx.strokeRect(x+.5,125.5,139,99);ctx.fillText(`${i+1}`,x+70,150);ctx.font="10px monospace";ctx.fillText(o.n,x+70,185);ctx.font="bold 18px monospace"});ctx.textAlign="left"}
loop=(t)=>{let dt=Math.min((t-this.last)/1000,.05);this.last=t;this.u(dt);this.draw();this.input.end();requestAnimationFrame(this.loop)}
start(){loading.classList.add("hidden");requestAnimationFrame(this.loop)}
}
const M={idle:"assets/player/idle.png",run:"assets/player/run.png",attack:"assets/player/attack.png",slime:"assets/enemies/slime.png",archer:"assets/enemies/archer.png",lancer:"assets/enemies/lancer.png",boss:"assets/enemies/middle_boss.png",grass:"assets/tiles/grass.png",bed:"assets/objects/bed.png",a1:"assets/fx/alpha_1.png",a2:"assets/fx/alpha_2.png",a3:"assets/fx/alpha_3.png",a4:"assets/fx/alpha_4.png",circle:"assets/fx/circle.png",spirit:"assets/fx/spirit.png",aura:"assets/fx/aura.png",barBase:"assets/ui/bar_base.png",barFill:"assets/ui/bar_fill.png",sq:"assets/skills/q.png",sw:"assets/skills/w.png",se:"assets/skills/e.png",sr:"assets/skills/r.png"};
(async()=>{try{new Game(await new Assets(M).load()).start()}catch(e){console.error(e);loadingText.textContent=e.message}})();
