
"use strict";
const C={W:640,H:360,WW:2304,WH:1536,PS:155,ES:45,QR:300,QD:.8,QS:4,QCD:16,WCD:9,WMAX:3,ECD:13,SPAWN:2.1,MAXE:28};
const canvas=document.querySelector("#game"),ctx=canvas.getContext("2d",{alpha:false}),loading=document.querySelector("#loading"),loadingText=document.querySelector("#loadingText");ctx.imageSmoothingEnabled=false;
class Assets{constructor(m){this.m=m;this.i={}}async load(){let n=0,e=Object.entries(this.m);await Promise.all(e.map(([k,s])=>new Promise((o,f)=>{let i=new Image;i.onload=()=>{this.i[k]=i;loadingText.textContent=`에셋 불러오는 중… ${++n}/${e.length}`;o()};i.onerror=()=>f(Error(`로드 실패: ${s}`));i.src=s})));return this.i}}
class Input{constructor(){this.d=new Set;this.p=new Set;addEventListener("keydown",e=>{let k=e.key.toLowerCase();if(!this.d.has(k))this.p.add(k);this.d.add(k);if(["arrowup","arrowdown","arrowleft","arrowright","a","q","w","e","1","2","3"].includes(k))e.preventDefault()});addEventListener("keyup",e=>this.d.delete(e.key.toLowerCase()))}held(k){return this.d.has(k)}tap(k){return this.p.has(k)}end(){this.p.clear()}}
class Camera{constructor(){this.x=0;this.y=0}follow(t,dt){let s=1-Math.exp(-9*dt);this.x+=(t.x-C.W/2-this.x)*s;this.y+=(t.y-C.H/2-this.y)*s;this.x=Math.max(0,Math.min(C.WW-C.W,this.x));this.y=Math.max(0,Math.min(C.WH-C.H,this.y))}screen(x,y){return{x:Math.round(x-this.x),y:Math.round(y-this.y)}}}
class Anim{constructor(i,w,h,n,f,l=true){Object.assign(this,{i,w,h,n,f,l});this.reset()}reset(){this.fr=0;this.t=0;this.done=false}update(dt){if(this.done)return;this.t+=dt;while(this.t>=1/this.f){this.t-=1/this.f;if(++this.fr>=this.n){if(this.l)this.fr=0;else{this.fr=this.n-1;this.done=true}}}}draw(c,x,y,s=1,flip=false,a=1,tint=null){c.save();c.globalAlpha=a;c.translate(Math.round(x),Math.round(y));if(flip)c.scale(-1,1);let W=this.w*s,H=this.h*s;c.drawImage(this.i,this.fr*this.w,0,this.w,this.h,-W/2,-H*.78,W,H);if(tint){c.globalCompositeOperation="source-atop";c.globalAlpha=.38;c.fillStyle=tint;c.fillRect(-W/2,-H*.78,W,H)}c.restore()}}
class FX{constructor(type,x,y,a=0,d=.2){Object.assign(this,{type,x,y,a,d});this.life=d}update(dt){this.life-=dt}draw(c,cam){let p=cam.screen(this.x,this.y),t=Math.max(0,this.life/this.d);c.save();c.translate(p.x,p.y);c.rotate(this.a);c.globalAlpha=t;if(this.type==="slash"||this.type==="alpha"){c.strokeStyle=this.type==="alpha"?"#fffbd0":"#e7efd0";c.lineWidth=this.type==="alpha"?4:3;c.beginPath();c.arc(0,0,this.type==="alpha"?30:22,-1.05,1.05);c.stroke()}else if(this.type==="cosmic"){c.strokeStyle="#69bfff";c.lineWidth=5;c.shadowColor="#3c8cff";c.shadowBlur=10;c.beginPath();c.arc(0,0,38,-1.25,1.25);c.stroke();c.strokeStyle="#c9eeff";c.lineWidth=2;c.beginPath();c.arc(0,0,27,-1.1,1.1);c.stroke()}else{c.fillStyle="#fff";for(let i=0;i<5;i++){c.rotate(1.256);c.fillRect(8,0,10*t,2)}}c.restore()}}
class Enemy{constructor(img,x,y,id,l=1){this.x=x;this.y=y;this.id=id;this.level=l;this.max=3+Math.floor(l*.7);this.hp=this.max;this.dead=false;this.rewarded=false;this.flash=0;this.touch=0;this.anim=new Anim(img,32,32,4,6)}damage(n,fx,px,py){if(this.dead)return false;this.hp-=n;this.flash=.1;let dx=this.x-px,dy=this.y-py,d=Math.hypot(dx,dy)||1;this.x+=dx/d*9;this.y+=dy/d*9;fx.push(new FX("hit",this.x,this.y-8,0,.12));if(this.hp<=0)this.dead=true;return true}update(dt,p){if(this.dead)return;this.anim.update(dt);this.flash=Math.max(0,this.flash-dt);this.touch=Math.max(0,this.touch-dt);let dx=p.x-this.x,dy=p.y-this.y,d=Math.hypot(dx,dy)||1;if(!p.q.on&&!p.med){this.x+=dx/d*(C.ES+this.level*.5)*dt;this.y+=dy/d*(C.ES+this.level*.5)*dt}if(d<23&&this.touch<=0&&!p.q.on){p.hurt(8+Math.floor(this.level/4));this.touch=.75}}draw(c,cam){if(this.dead)return;let p=cam.screen(this.x,this.y);c.fillStyle="rgba(0,0,0,.25)";c.beginPath();c.ellipse(p.x,p.y+3,10,4,0,0,Math.PI*2);c.fill();this.anim.draw(c,p.x,p.y,1.25,false,this.flash>0?.45:1);c.fillStyle="#25120f";c.fillRect(p.x-13,p.y-22,26,3);c.fillStyle="#d95b45";c.fillRect(p.x-13,p.y-22,26*this.hp/this.max,3)}}
class Player{
constructor(i){this.i=i;this.sx=C.WW/2;this.sy=C.WH/2;this.x=this.sx;this.y=this.sy;this.level=1;this.xp=0;this.need=35;this.gold=0;this.maxHp=100;this.hp=100;this.atk=1;this.left=false;this.state="idle";this.hit=false;this.inv=0;this.a={idle:new Anim(i.idle,96,96,10,8),run:new Anim(i.run,96,96,16,15),attack:new Anim(i.attack,96,96,7,15,false)};this.q={on:false,t:0,next:0,count:0,cd:0,lv:1,targets:[]};this.w={cd:0,lv:1};this.e={cd:0,lv:0,open:false};this.med=false;this.medT=0;this.choices=[]}
resetPos(){this.x=this.sx;this.y=this.sy}
hurt(n){if(this.inv>0||this.q.on)return;this.hp=Math.max(0,this.hp-n);this.inv=.35}
reward(g,x){this.gold+=g;this.xp+=x;if(this.xp>=this.need){this.xp-=this.need;this.level++;this.need=Math.floor(this.need*1.32+8);this.makeChoices()}}
makeChoices(){let p=[{id:"q",n:"알파 강화",d:"피해 +1, 사거리 +20"},{id:"w",n:"명상 강화",d:"회복량 증가"},{id:"hp",n:"체력 단련",d:"최대 체력 +20"},{id:"atk",n:"검술 숙련",d:"평타 피해 +1"}];p.push(this.e.open?{id:"e",n:"우주류 강화",d:"피해와 범위 증가"}:{id:"eu",n:"우주류 해금",d:"E 스킬 사용 가능"});p.sort(()=>Math.random()-.5);this.choices=p.slice(0,3)}
choose(i){let c=this.choices[i];if(!c)return;if(c.id==="q")this.q.lv++;if(c.id==="w")this.w.lv++;if(c.id==="hp"){this.maxHp+=20;this.hp=Math.min(this.maxHp,this.hp+35)}if(c.id==="atk")this.atk++;if(c.id==="eu"){this.e.open=true;this.e.lv=1}if(c.id==="e")this.e.lv++;this.choices=[]}
cancel(){this.state="idle";this.a.attack.reset();this.hit=false}
startW(){if(this.w.cd>0||this.q.on)return;this.cancel();this.med=true;this.medT=0;this.w.cd=C.WCD}
near(es,r=C.QR){return es.filter(e=>!e.dead&&Math.hypot(e.x-this.x,e.y-this.y)<=r).sort((a,b)=>Math.hypot(a.x-this.x,a.y-this.y)-Math.hypot(b.x-this.x,b.y-this.y))}
startQ(es){if(this.q.cd>0||this.q.on||this.med)return;let r=C.QR+20*(this.q.lv-1),t=this.near(es,r);if(!t.length)return;this.cancel();this.q={on:true,t:0,next:0,count:0,cd:C.QCD,lv:this.q.lv,targets:t}}
strikeQ(es,fx){let r=C.QR+20*(this.q.lv-1),ts=this.q.targets.filter(e=>!e.dead&&Math.hypot(e.x-this.x,e.y-this.y)<=r);if(!ts.length)ts=this.near(es,r);if(!ts.length)return;let t=ts[this.q.count%ts.length],d=Math.hypot(t.x-this.x,t.y-this.y);if(d>r)return;let a=Math.atan2(t.y-this.y,t.x-this.x);this.x=t.x-Math.cos(a)*18;this.y=t.y-Math.sin(a)*18;t.damage(1+this.q.lv,fx,this.x,this.y);fx.push(new FX("alpha",t.x,t.y,a,.22));this.q.count++}
castE(es,fx){if(!this.e.open||this.e.cd>0||this.q.on||this.med)return;this.cancel();this.e.cd=C.ECD;let dir=this.left?-1:1,cx=this.x+dir*45,r=65+10*(this.e.lv-1);fx.push(new FX("cosmic",cx,this.y-4,this.left?Math.PI:0,.42));for(let e of es)if(!e.dead&&Math.hypot(e.x-cx,e.y-this.y)<=r)e.damage(2+this.e.lv,fx,this.x,this.y)}
update(dt,input,es,fx){
this.inv=Math.max(0,this.inv-dt);this.q.cd=Math.max(0,this.q.cd-dt);this.w.cd=Math.max(0,this.w.cd-dt);this.e.cd=Math.max(0,this.e.cd-dt);
if(input.tap("q"))this.startQ(es);if(input.tap("w"))this.startW();if(input.tap("e"))this.castE(es,fx);
if(this.q.on){this.q.t+=dt;while(this.q.count<C.QS&&this.q.t>=this.q.next){this.strikeQ(es,fx);this.q.next+=C.QD/C.QS}if(this.q.t>=C.QD){this.q.on=false;this.state="idle"}return}
if(this.med){this.medT+=dt;this.hp=Math.min(this.maxHp,this.hp+(8+5*this.w.lv)*dt);if(this.medT>=C.WMAX||input.held("arrowup")||input.held("arrowdown")||input.held("arrowleft")||input.held("arrowright")||input.tap("a")||input.tap("q")||input.tap("e")){this.med=false;this.medT=0}return}
if(input.tap("a")){this.state="attack";this.a.attack.reset();this.hit=false}
if(this.state==="attack"&&!this.a.attack.done){this.a.attack.update(dt);if(!this.hit&&this.a.attack.fr>=3){this.hit=true;let dir=this.left?-1:1,cx=this.x+dir*30,hits=0;fx.push(new FX("slash",cx,this.y-5,this.left?Math.PI:0,.14));for(let e of es)if(!e.dead&&Math.hypot(e.x-cx,e.y-this.y)<43&&e.damage(this.atk,fx,this.x,this.y))hits++;if(hits)this.q.cd=Math.max(0,this.q.cd-2*hits)}if(this.a.attack.done)this.state="idle";return}
let dx=0,dy=0;if(input.held("arrowleft"))dx--;if(input.held("arrowright"))dx++;if(input.held("arrowup"))dy--;if(input.held("arrowdown"))dy++;if(dx||dy){let l=Math.hypot(dx,dy);dx/=l;dy/=l;this.x+=dx*C.PS*dt;this.y+=dy*C.PS*dt;if(dx<0)this.left=true;if(dx>0)this.left=false;this.state="run"}else this.state="idle";this.x=Math.max(35,Math.min(C.WW-35,this.x));this.y=Math.max(35,Math.min(C.WH-35,this.y));this.a[this.state].update(dt)}
aura(c,cam){let p=cam.screen(this.x,this.y),u=1+Math.sin(performance.now()/120)*.12;c.save();c.globalCompositeOperation="screen";for(let i=0;i<3;i++){c.globalAlpha=.18-i*.04;c.fillStyle="#55ff78";c.beginPath();c.ellipse(p.x,p.y-7,28*u+i*7,38*u+i*7,0,0,Math.PI*2);c.fill()}c.globalAlpha=.75;c.strokeStyle="#8dff9f";c.lineWidth=2;c.beginPath();c.arc(p.x,p.y-8,24*u,0,Math.PI*2);c.stroke();c.restore()}
draw(c,cam){if(this.q.on)return;let p=cam.screen(this.x,this.y);if(this.med)this.aura(c,cam);c.fillStyle="rgba(0,0,0,.28)";c.beginPath();c.ellipse(p.x,p.y+4,18,7,0,0,Math.PI*2);c.fill();this.a[this.state==="attack"?"attack":this.state].draw(c,p.x,p.y,1.35,this.left,this.inv>0?.55:1,this.e.open&&this.e.cd<=0?"#5ebcff":null)}
}
class World{constructor(i){this.i=i;this.p=[];let r=this.rand(80231),cx=C.WW/2,cy=C.WH/2;for(let n=0;n<115;n++){let x=50+r()*(C.WW-100),y=50+r()*(C.WH-100);if(Math.hypot(x-cx,y-cy)<170)continue;this.p.push({t:r()<.42?"c":"r",x,y,f:Math.floor(r()*4)})}this.p.sort((a,b)=>a.y-b.y)}rand(s){return()=>((s=Math.imul(1664525,s)+1013904223>>>0)/4294967296)}ground(c,cam){let sx=Math.floor(cam.x/16)*16,sy=Math.floor(cam.y/16)*16;for(let y=sy;y<cam.y+C.H+16;y+=16)for(let x=sx;x<cam.x+C.W+16;x+=16){let p=cam.screen(x,y);c.drawImage(this.i.grass,p.x,p.y,16,16);let h=((x*31+y*17)>>4)&31;if(h===0)c.drawImage(this.i.plains,0,64,16,16,p.x,p.y,16,16);if(h===7)c.drawImage(this.i.decor,16,0,16,16,p.x,p.y,16,16)}}prop(c,cam,o){let p=cam.screen(o.x,o.y);if(p.x<-40||p.y<-40||p.x>680||p.y>400)return;o.t==="c"?c.drawImage(this.i.chest,o.f*16,0,16,16,p.x-8,p.y-14,16,16):c.drawImage(this.i.rock,0,0,16,16,p.x-8,p.y-13,16,16)}}
class Game{
constructor(i){this.i=i;this.input=new Input;this.cam=new Camera;this.world=new World(i);this.p=new Player(i);this.es=[];this.fx=[];this.sp=0;this.id=0;this.last=performance.now();for(let n=0;n<8;n++)this.spawn()}
spawn(){if(this.es.filter(e=>!e.dead).length>=C.MAXE)return;let a=Math.random()*Math.PI*2,d=230+Math.random()*170,x=Math.max(40,Math.min(C.WW-40,this.p.x+Math.cos(a)*d)),y=Math.max(40,Math.min(C.WH-40,this.p.y+Math.sin(a)*d));this.es.push(new Enemy(this.i.slime,x,y,this.id++,this.p.level))}
reset(){this.p=new Player(this.i);this.es=[];this.fx=[];this.sp=0;for(let n=0;n<8;n++)this.spawn()}
update(dt){if(this.p.choices.length){if(this.input.tap("1"))this.p.choose(0);if(this.input.tap("2"))this.p.choose(1);if(this.input.tap("3"))this.p.choose(2);return}if(this.input.tap("r"))this.reset();this.sp+=dt;if(this.sp>=C.SPAWN){this.sp=0;this.spawn()}this.p.update(dt,this.input,this.es,this.fx);for(let e of this.es)e.update(dt,this.p);for(let f of this.fx)f.update(dt);this.fx=this.fx.filter(f=>f.life>0);for(let e of this.es)if(e.dead&&!e.rewarded){e.rewarded=true;this.p.reward(3+Math.floor(e.level*.5),8+e.level*2)}if(this.es.length>80)this.es=this.es.filter(e=>!e.dead);this.cam.follow(this.p,dt);if(this.p.hp<=0)this.reset()}
draw(){this.world.ground(ctx,this.cam);let l=[];for(let o of this.world.p)l.push({y:o.y,d:()=>this.world.prop(ctx,this.cam,o)});for(let e of this.es)if(!e.dead)l.push({y:e.y,d:()=>e.draw(ctx,this.cam)});if(!this.p.q.on)l.push({y:this.p.y,d:()=>this.p.draw(ctx,this.cam)});l.sort((a,b)=>a.y-b.y);for(let x of l)x.d();for(let f of this.fx)f.draw(ctx,this.cam);this.hud();if(this.p.choices.length)this.menu()}
bar(x,y,w,h,r,b,f){ctx.fillStyle=b;ctx.fillRect(x,y,w,h);ctx.fillStyle=f;ctx.fillRect(x,y,w*Math.max(0,Math.min(1,r)),h);ctx.strokeStyle="rgba(255,255,255,.35)";ctx.strokeRect(x+.5,y+.5,w-1,h-1)}
hud(){let p=this.p,cd=v=>v>0?v.toFixed(1):"READY";ctx.fillStyle="rgba(8,14,9,.86)";ctx.fillRect(8,8,248,82);ctx.strokeStyle="rgba(210,235,182,.45)";ctx.strokeRect(8.5,8.5,247,81);ctx.fillStyle="#eef5d8";ctx.font="bold 10px monospace";ctx.fillText(`PROJECT RONIN v0.3.0  LV.${p.level}`,16,22);this.bar(16,29,150,8,p.hp/p.maxHp,"#321718","#d45f57");ctx.font="8px monospace";ctx.fillStyle="#fff";ctx.fillText(`${Math.ceil(p.hp)} / ${p.maxHp}`,171,36);this.bar(16,43,150,6,p.xp/p.need,"#182433","#5ca8e6");ctx.fillStyle="#c6dcb1";ctx.fillText(`XP ${p.xp}/${p.need}   GOLD ${p.gold}`,16,60);ctx.fillText(`Q ${cd(p.q.cd)}  W ${cd(p.w.cd)}  E ${p.e.open?cd(p.e.cd):"LOCKED"}`,16,75);ctx.fillText(`ENEMIES ${this.es.filter(e=>!e.dead).length}`,172,75);if(p.med){ctx.fillStyle="#8dff9f";ctx.fillText(`MEDITATING ${Math.max(0,C.WMAX-p.medT).toFixed(1)}`,470,25)}if(p.q.on){ctx.fillStyle="rgba(245,242,208,.14)";ctx.fillRect(0,0,C.W,C.H);ctx.fillStyle="#fffbd0";ctx.font="bold 13px monospace";ctx.fillText("ALPHA STRIKE",C.W/2-48,26)}}
menu(){let a=this.p.choices;ctx.fillStyle="rgba(3,6,5,.82)";ctx.fillRect(0,0,C.W,C.H);ctx.fillStyle="#eef5d8";ctx.font="bold 20px monospace";ctx.textAlign="center";ctx.fillText(`LEVEL ${this.p.level}`,C.W/2,72);ctx.font="10px monospace";ctx.fillStyle="#b9cfa5";ctx.fillText("1 / 2 / 3 중 하나를 선택하세요",C.W/2,92);a.forEach((o,i)=>{let x=82+i*164,y=125,w=148,h=112;ctx.fillStyle="#101a12";ctx.fillRect(x,y,w,h);ctx.strokeStyle="#8fb66f";ctx.lineWidth=2;ctx.strokeRect(x+.5,y+.5,w-1,h-1);ctx.fillStyle="#eef5d8";ctx.font="bold 14px monospace";ctx.fillText(String(i+1),x+w/2,y+24);ctx.font="bold 10px monospace";ctx.fillText(o.n,x+w/2,y+52);ctx.font="9px monospace";ctx.fillStyle="#a9c59a";ctx.fillText(o.d,x+w/2,y+78)});ctx.textAlign="left"}
loop=(t)=>{let dt=Math.min((t-this.last)/1000,.05);this.last=t;this.update(dt);this.draw();this.input.end();requestAnimationFrame(this.loop)}
start(){loading.classList.add("hidden");requestAnimationFrame(this.loop)}
}
const manifest={idle:"assets/player/idle.png",run:"assets/player/run.png",attack:"assets/player/attack.png",slime:"assets/enemies/slime.png",grass:"assets/tiles/grass.png",plains:"assets/tiles/plains.png",decor:"assets/tiles/decor.png",chest:"assets/objects/chest.png",rock:"assets/objects/rock.png"};
(async()=>{try{new Game(await new Assets(manifest).load()).start()}catch(e){console.error(e);loadingText.textContent=e.message}})();
