
"use strict";
const C={W:640,H:360,WW:2304,WH:1536,PS:155,AR:48,SPAWN:2.1,MAXE:34};
const V={x:702,y:420,w:900,h:650,gateX:1152,gateW:110};
const canvas=document.querySelector("#game"),ctx=canvas.getContext("2d",{alpha:false}),loading=document.querySelector("#loading"),loadingText=document.querySelector("#loadingText");ctx.imageSmoothingEnabled=false;
class Loader{constructor(m){this.m=m;this.i={}}async load(){let n=0,e=Object.entries(this.m);await Promise.all(e.map(([k,s])=>new Promise(ok=>{let im=new Image;im.onload=()=>{this.i[k]=im;loadingText.textContent=`에셋 ${++n}/${e.length}`;ok()};im.onerror=()=>{console.error(s);let c=document.createElement("canvas");c.width=c.height=1;this.i[k]=c;loadingText.textContent=`에셋 ${++n}/${e.length}`;ok()};im.src=s})));return this.i}}
class AudioSys{constructor(){this.b={};this.l={};this.ready=false}add(k,s,v=.5,loop=false){let a=new Audio(s);a.volume=v;a.loop=loop;this.b[k]=a}unlock(){if(this.ready)return;this.ready=true;this.playLoop("bgm")}play(k){this.unlock();let a=this.b[k];if(!a)return;let c=a.cloneNode();c.volume=a.volume;c.play().catch(()=>{})}playLoop(k){if(this.l[k])return;let a=this.b[k];if(!a)return;let c=a.cloneNode();c.loop=true;c.volume=a.volume;this.l[k]=c;c.play().catch(()=>{})}stopLoop(k){let a=this.l[k];if(a){a.pause();a.currentTime=0;delete this.l[k]}}}
class Input{constructor(a){this.d=new Set;this.p=new Set;addEventListener("keydown",e=>{a.unlock();let k=e.key.toLowerCase();if(!this.d.has(k))this.p.add(k);this.d.add(k);if(["arrowup","arrowdown","arrowleft","arrowright","a","q","w","e","r","f","1","2","3"].includes(k))e.preventDefault()});addEventListener("keyup",e=>this.d.delete(e.key.toLowerCase()));addEventListener("pointerdown",()=>a.unlock())}held(k){return this.d.has(k)}tap(k){return this.p.has(k)}end(){this.p.clear()}}
class Cam{constructor(){this.x=0;this.y=0}follow(p,dt){let s=1-Math.exp(-9*dt);this.x+=(p.x-C.W/2-this.x)*s;this.y+=(p.y-C.H/2-this.y)*s;this.x=Math.max(0,Math.min(C.WW-C.W,this.x));this.y=Math.max(0,Math.min(C.WH-C.H,this.y))}s(x,y){return{x:Math.round(x-this.x),y:Math.round(y-this.y)}}}
class Anim{constructor(img,fw,fh,n,f,loop=true){Object.assign(this,{img,fw,fh,n,f,loop});this.reset()}reset(){this.fr=0;this.t=0;this.done=false}u(dt,sp=1){if(this.done)return;this.t+=dt*sp;while(this.t>=1/this.f){this.t-=1/this.f;if(++this.fr>=this.n){if(this.loop)this.fr=0;else{this.fr=this.n-1;this.done=true}}}}d(c,x,y,sc=1,flip=false,a=1){c.save();c.globalAlpha=a;c.translate(Math.round(x),Math.round(y));if(flip)c.scale(-1,1);let w=this.fw*sc,h=this.fh*sc;c.drawImage(this.img,this.fr*this.fw,0,this.fw,this.fh,-w/2,-h*.78,w,h);c.restore()}}
class FX{constructor(img,fw,fh,n,x,y,sc=1,d=.35,flip=false){Object.assign(this,{img,fw,fh,n,x,y,sc,d,flip});this.life=d}u(dt){this.life-=dt}d0(c,cam){let p=cam.s(this.x,this.y),f=Math.min(this.n-1,Math.floor((1-this.life/this.d)*this.n));c.save();c.translate(p.x,p.y);if(this.flip)c.scale(-1,1);c.globalAlpha=Math.max(0,Math.min(1,this.life/.06));c.drawImage(this.img,f*this.fw,0,this.fw,this.fh,-this.fw*this.sc/2,-this.fh*this.sc/2,this.fw*this.sc,this.fh*this.sc);c.restore()}}
function inVillage(x,y){return x>V.x&&x<V.x+V.w&&y>V.y&&y<V.y+V.h}
function inGate(x,y){return y>V.y+V.h-30&&x>V.gateX-V.gateW/2&&x<V.gateX+V.gateW/2}
class Projectile{constructor(img,x,y,vx,vy,damage){Object.assign(this,{img,x,y,vx,vy,damage});this.dead=false;this.life=3;this.a=Math.atan2(vy,vx)}u(dt,p){this.x+=this.vx*dt;this.y+=this.vy*dt;this.life-=dt;if(this.life<=0||inVillage(this.x,this.y)){this.dead=true;return}if(Math.hypot(this.x-p.x,this.y-p.y)<14){p.hurt(this.damage);this.dead=true}}d(c,cam){let p=cam.s(this.x,this.y);c.save();c.translate(p.x,p.y);c.rotate(this.a);c.drawImage(this.img,-16,-16,32,32);c.restore()}}
class NPC{constructor(img,x,y,name){this.x=x;this.y=y;this.name=name;this.a=new Anim(img,16,16,4,6)}u(dt){this.a.u(dt)}d(c,cam){let p=cam.s(this.x,this.y);this.a.d(c,p.x,p.y,2,false);c.fillStyle="#f1eed1";c.font="8px monospace";c.textAlign="center";c.fillText(this.name,p.x,p.y-28);c.textAlign="left"}}
class Enemy{
constructor(type,i,x,y,l=1){this.type=type;this.x=x;this.y=y;this.dead=false;this.rewarded=false;this.state="move";this.attackTime=0;this.hitDone=false;this.left=false;
let q={slime:{hp:5,sp:43,r:22,wind:.32,rec:.42,atk:8,sc:1.25,m:[i.slime,32,32,4,6],a:[i.slime,32,32,4,8]},
archer:{hp:8,sp:37,r:145,wind:.52,rec:.65,atk:9,sc:.28,m:[i.archer,192,192,4,7],a:[i.archerAttack,192,192,8,11]},
lancer:{hp:12,sp:50,r:34,wind:.4,rec:.5,atk:12,sc:.24,m:[i.lancer,320,320,6,8],a:[i.lancerAttack,320,320,3,8]},
boss:{hp:48,sp:34,r:42,wind:.55,rec:.7,atk:18,sc:1.05,m:[i.boss,120,80,10,8],a:[i.bossAttack,120,80,4,7]}}[type];
Object.assign(this,q);this.max=this.hp+l;this.hp=this.max;this.move=new Anim(...q.m,true);this.attack=new Anim(...q.a,false);this.flash=0}
takeDamage(n){if(this.dead)return false;this.hp-=n;this.flash=.12;if(this.hp<=0)this.dead=true;return true}
startAttack(){this.state="attack";this.attackTime=0;this.hitDone=false;this.attack.reset()}
u(dt,p,projectiles,i){if(this.dead)return;this.flash=Math.max(0,this.flash-dt);let dx=p.x-this.x,dy=p.y-this.y,d=Math.hypot(dx,dy)||1;this.left=dx<0;
if(this.state==="attack"){this.attackTime+=dt;this.attack.u(dt);if(!this.hitDone&&this.attackTime>=this.wind){this.hitDone=true;if(this.type==="archer"){let vx=dx/d*190,vy=dy/d*190;projectiles.push(new Projectile(i.arrow,this.x,this.y-10,vx,vy,this.atk))}else if(Math.hypot(p.x-this.x,p.y-this.y)<=this.r+8)p.hurt(this.atk)}if(this.attackTime>=this.wind+this.rec){this.state="move";this.attack.reset()}return}
if(d<=this.r){this.startAttack();return}
this.state="move";this.move.u(dt);let nx=this.x+dx/d*this.sp*dt,ny=this.y+dy/d*this.sp*dt;if(!inVillage(nx,ny)){this.x=nx;this.y=ny}}
d(c,cam){if(this.dead)return;let p=cam.s(this.x,this.y),an=this.state==="attack"?this.attack:this.move;c.save();c.globalAlpha=this.flash>0?.45:1;an.d(c,p.x,p.y,this.sc,this.left);c.restore();let w=this.type==="boss"?70:28,y=p.y-(this.type==="boss"?47:24);c.fillStyle="#291719";c.fillRect(p.x-w/2,y,w,4);c.fillStyle=this.type==="boss"?"#b44af2":"#df5f49";c.fillRect(p.x-w/2,y,w*this.hp/this.max,4)}
}
class Player{
constructor(i,a){this.i=i;this.audio=a;this.x=V.gateX;this.y=V.y+V.h-120;this.hp=100;this.maxHp=100;this.gold=0;this.xp=0;this.need=35;this.level=1;this.atk=1;this.left=false;this.state="idle";this.inv=0;this.hit=false;this.med=false;this.medT=0;this.attackSoundIndex=0;this.q={open:false,cd:0,on:false,t:0,count:0};this.w={open:false,cd:0};this.e={open:false,cd:0,on:false,t:0};this.r={open:false,cd:0,on:false,t:0};this.choices=[];this.an={idle:new Anim(i.idle,96,96,10,8),run:new Anim(i.run,96,96,16,15),attack:new Anim(i.attack,96,96,7,15,false)}}
hurt(n){if(this.inv>0||this.q.on)return;this.hp=Math.max(0,this.hp-n);this.inv=.35;if(this.med)this.stopMed()}
gainXP(n){this.xp+=n;while(this.xp>=this.need){this.xp-=this.need;this.level++;this.need=Math.floor(this.need*1.3+8);this.makeChoices();this.audio.play("level")}}
reward(g,x){this.gold+=g;this.gainXP(x)}
makeChoices(){let p=[];for(let [k,n] of [["q","알파"],["w","명상"],["e","우주류"],["r","최후의 전사"]])p.push({id:k,n:(this[k].open?"강화 ":"해금 ")+n});p.push({id:"hp",n:"체력 +20"},{id:"atk",n:"평타 +1"});p.sort(()=>Math.random()-.5);this.choices=p.slice(0,3)}
choose(n){let c=this.choices[n];if(!c)return;if("qwer".includes(c.id))this[c.id].open=true;else if(c.id==="hp"){this.maxHp+=20;this.hp+=20}else this.atk++;this.choices=[]}
stopMed(){this.med=false;this.medT=0;this.audio.stopLoop("meditate");this.state="idle"}
u(dt,input,es,fx){this.inv=Math.max(0,this.inv-dt);for(let k of "qwer")this[k].cd=Math.max(0,this[k].cd-dt);if(this.e.on&&(this.e.t-=dt)<=0)this.e.on=false;if(this.r.on&&(this.r.t-=dt)<=0){this.r.on=false;this.audio.stopLoop("ultimate")}
if(input.tap("w")&&this.w.open&&this.w.cd<=0){if(this.med)this.stopMed();else{this.med=true;this.medT=0;this.w.cd=9;this.state="meditate";this.audio.playLoop("meditate")}}
if(input.tap("e")&&this.e.open&&this.e.cd<=0&&!this.med){this.e.cd=13;this.e.on=true;this.e.t=5;fx.push(new FX(this.i.circle,16,32,8,this.x,this.y,2.5,.5))}
if(input.tap("r")&&this.r.open&&this.r.cd<=0&&!this.med){this.r.cd=35;this.r.on=true;this.r.t=9;this.audio.playLoop("ultimate")}
if(input.tap("q")&&this.q.open&&this.q.cd<=0&&!this.med){let t=es.filter(e=>!e.dead&&Math.hypot(e.x-this.x,e.y-this.y)<290);if(t.length){this.q.cd=16;this.q.on=true;this.q.t=0;this.q.count=0;this.audio.play("alpha")}}
if(this.q.on){this.q.t+=dt;while(this.q.count<4&&this.q.t>=this.q.count*.2){let ts=es.filter(e=>!e.dead&&Math.hypot(e.x-this.x,e.y-this.y)<290);if(ts.length){let t=ts[this.q.count%ts.length],a=Math.atan2(t.y-this.y,t.x-this.x);this.x=t.x-Math.cos(a)*18;this.y=t.y-Math.sin(a)*18;t.takeDamage(2);fx.push(new FX([this.i.a1,this.i.a2,this.i.a3,this.i.a4][this.q.count%4],32,32,4,t.x,t.y,1.7,.28,this.q.count%2))}this.q.count++}if(this.q.t>=.8){this.q.on=false;this.state="idle"}return}
if(this.med){this.medT+=dt;this.hp=Math.min(this.maxHp,this.hp+14*dt);if(this.medT>=3||input.tap("a")||input.held("arrowup")||input.held("arrowdown")||input.held("arrowleft")||input.held("arrowright"))this.stopMed();return}
if(input.tap("a")&&this.state!=="attack"){this.state="attack";this.hit=false;this.an.attack.reset()}
if(this.state==="attack"){this.an.attack.u(dt,this.r.on?1.6:1);if(!this.hit&&this.an.attack.fr>=3){this.hit=true;this.attackSoundIndex=(this.attackSoundIndex%3)+1;this.audio.play("attack"+this.attackSoundIndex);let range=C.AR+(this.r.on?22:0);for(let e of es)if(!e.dead&&Math.hypot(e.x-this.x,e.y-this.y)<=range){e.takeDamage(this.atk+(this.e.on?3:0));this.q.cd=Math.max(0,this.q.cd-2)}}if(this.an.attack.done){this.state="idle";this.an.attack.reset()}return}
let dx=0,dy=0;if(input.held("arrowleft"))dx--;if(input.held("arrowright"))dx++;if(input.held("arrowup"))dy--;if(input.held("arrowdown"))dy++;
if(dx||dy){let l=Math.hypot(dx,dy),sp=155*(this.r.on?1.45:1);dx/=l;dy/=l;let nx=this.x+dx*sp*dt,ny=this.y+dy*sp*dt;let inside=inVillage(this.x,this.y),nextInside=inVillage(nx,ny);if(inside&&!nextInside&&!inGate(nx,ny)){nx=this.x;ny=this.y}this.x=Math.max(30,Math.min(C.WW-30,nx));this.y=Math.max(30,Math.min(C.WH-30,ny));if(dx<0)this.left=true;if(dx>0)this.left=false;this.state="run";this.an.run.u(dt)}else{this.state="idle";this.an.idle.u(dt)}}
drawMeditation(c,cam){let p=cam.s(this.x,this.y),t=performance.now()/1000;
c.save();c.globalCompositeOperation="screen";
let f1=Math.floor(t*10)%8;c.globalAlpha=.92;c.drawImage(this.i.med1,f1*72,0,72,72,p.x-54,p.y-66,108,108);
let f2=Math.floor(t*13)%9;for(let j=0;j<5;j++){let a=t*1.5+j*1.256,r=24+(j%2)*8;c.globalAlpha=.8;c.drawImage(this.i.med2,f2*8,0,8,13,p.x+Math.cos(a)*r-8,p.y-18+Math.sin(a)*15-13,16,26)}
let f3=Math.floor(t*15)%9;for(let j=0;j<7;j++){let a=-t*1.9+j*.897,r=18+(j%3)*7;c.globalAlpha=.78;c.drawImage(this.i.med3,f3*8,0,8,7,p.x+Math.cos(a)*r-8,p.y+4+Math.sin(a)*18-7,16,14)}
c.restore()}
d(c,cam){if(this.q.on)return;let p=cam.s(this.x,this.y),an=this.an[this.state==="run"?"run":this.state==="attack"?"attack":"idle"];if(this.med)this.drawMeditation(c,cam);an.d(c,p.x,p.y,1.35,this.left,this.inv>0?.55:1);if(this.e.on){c.save();c.strokeStyle="#62c6ff";c.lineWidth=4;c.shadowColor="#3d8cff";c.shadowBlur=8;c.beginPath();c.moveTo(p.x+(this.left?-14:14),p.y-31);c.lineTo(p.x+(this.left?-34:34),p.y+1);c.stroke();c.restore()}}
}
class Game{
constructor(i){this.i=i;this.audio=new AudioSys;for(let [k,s,v,l] of [["bgm","assets/audio/bgm.ogg",.3,true],["attack1","assets/audio/attack1.wav",.55],["attack2","assets/audio/attack2.wav",.55],["attack3","assets/audio/attack3.wav",.55],["alpha","assets/audio/alpha.wav",.65],["meditate","assets/audio/meditate.wav",.5,true],["ultimate","assets/audio/ultimate.wav",.65,true],["level","assets/audio/levelup.wav",.6]])this.audio.add(k,s,v,l);this.input=new Input(this.audio);this.cam=new Cam;this.p=new Player(i,this.audio);this.es=[];this.fx=[];this.proj=[];this.spawnT=0;this.kills=0;this.last=performance.now();this.aura={x:V.gateX,y:V.y+V.h/2,r:42};this.npcs=[new NPC(i.villager,V.x+250,V.y+250,"주민"),new NPC(i.oldman,V.x+520,V.y+300,"장로"),new NPC(i.monk,V.x+650,V.y+470,"수행승"),new NPC(i.hunter,V.x+340,V.y+500,"사냥꾼"),new NPC(i.princess,V.x+740,V.y+210,"영주")];this.buildings=[{img:i.castle,x:V.x+450,y:V.y+190,w:160,h:128},{img:i.house1,x:V.x+180,y:V.y+320,w:64,h:96},{img:i.house2,x:V.x+720,y:V.y+330,w:64,h:96},{img:i.monastery,x:V.x+680,y:V.y+570,w:96,h:150},{img:i.barracks,x:V.x+220,y:V.y+570,w:96,h:128}];for(let n=0;n<10;n++)this.spawn()}
spawn(){if(this.es.filter(e=>!e.dead).length>=C.MAXE)return;let type=Math.random()<.45?"slime":Math.random()<.55?"archer":"lancer";if(this.kills&&this.kills%15===0&&!this.es.some(e=>!e.dead&&e.type==="boss"))type="boss";let x,y;do{x=50+Math.random()*(C.WW-100);y=50+Math.random()*(C.WH-100)}while(inVillage(x,y)||Math.hypot(x-this.p.x,y-this.p.y)<220);this.es.push(new Enemy(type,this.i,x,y,this.p.level))}
u(dt){if(this.p.choices.length){if(this.input.tap("1"))this.p.choose(0);if(this.input.tap("2"))this.p.choose(1);if(this.input.tap("3"))this.p.choose(2);return}this.spawnT+=dt;if(this.spawnT>C.SPAWN){this.spawnT=0;this.spawn()}this.p.u(dt,this.input,this.es,this.fx);for(let e of this.es)e.u(dt,this.p,this.proj,this.i);for(let p of this.proj)p.u(dt,this.p);for(let f of this.fx)f.u(dt);for(let n of this.npcs)n.u(dt);this.proj=this.proj.filter(p=>!p.dead);this.fx=this.fx.filter(f=>f.life>0);if(Math.hypot(this.p.x-this.aura.x,this.p.y-this.aura.y)<this.aura.r)this.p.gainXP(18*dt);for(let e of this.es)if(e.dead&&!e.rewarded){e.rewarded=true;this.kills++;this.p.reward(e.type==="boss"?30:5,e.type==="boss"?35:10)}this.cam.follow(this.p,dt);if(this.p.hp<=0)location.reload()}
ground(){let sx=Math.floor(this.cam.x/16)*16,sy=Math.floor(this.cam.y/16)*16;for(let y=sy;y<this.cam.y+C.H+16;y+=16)for(let x=sx;x<this.cam.x+C.W+16;x+=16){let p=this.cam.s(x,y);ctx.drawImage(this.i.grass,p.x,p.y,16,16);let h=((x*31+y*17)>>4)&31;if(h===0)ctx.drawImage(this.i.plains,0,64,16,16,p.x,p.y,16,16);if(inVillage(x,y)){ctx.fillStyle="rgba(171,143,91,.16)";ctx.fillRect(p.x,p.y,16,16)}}
let pathX=V.gateX-36;for(let y=V.y+80;y<V.y+V.h+140;y+=16)for(let x=pathX;x<pathX+72;x+=16){let p=this.cam.s(x,y);ctx.drawImage(this.i.plains,16,16,16,16,p.x,p.y,16,16)}
ctx.strokeStyle="#5d4a2b";ctx.lineWidth=10;let a=this.cam.s(V.x,V.y),b=this.cam.s(V.x+V.w,V.y+V.h);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,a.y);ctx.lineTo(b.x,b.y);ctx.lineTo(this.cam.s(V.gateX+V.gateW/2,V.y+V.h).x,b.y);ctx.moveTo(this.cam.s(V.gateX-V.gateW/2,V.y+V.h).x,b.y);ctx.lineTo(a.x,b.y);ctx.closePath();ctx.stroke()}
bar(x,y,w,h,r,b,f){ctx.fillStyle=b;ctx.fillRect(x,y,w,h);ctx.fillStyle=f;ctx.fillRect(x,y,w*Math.max(0,Math.min(1,r)),h);ctx.strokeStyle="#e1e8cf";ctx.strokeRect(x+.5,y+.5,w-1,h-1)}
draw(){this.ground();let ap=this.cam.s(this.aura.x,this.aura.y);ctx.fillStyle="rgba(85,190,255,.18)";ctx.beginPath();ctx.arc(ap.x,ap.y,this.aura.r+Math.sin(performance.now()/180)*4,0,Math.PI*2);ctx.fill();ctx.strokeStyle="#79d9ff";ctx.stroke();ctx.fillStyle="#d8f4ff";ctx.font="8px monospace";ctx.fillText("테스트 XP 오라",ap.x-30,ap.y-50);let list=[];for(let b of this.buildings)list.push({y:b.y,d:()=>{let p=this.cam.s(b.x,b.y);ctx.drawImage(b.img,p.x-b.w/2,p.y-b.h,b.w,b.h)}});for(let n of this.npcs)list.push({y:n.y,d:()=>n.d(ctx,this.cam)});for(let e of this.es)if(!e.dead)list.push({y:e.y,d:()=>e.d(ctx,this.cam)});list.push({y:this.p.y,d:()=>this.p.d(ctx,this.cam)});list.sort((a,b)=>a.y-b.y);for(let o of list)o.d();for(let p of this.proj)p.d(ctx,this.cam);for(let f of this.fx)f.d0(ctx,this.cam);this.hud();if(this.p.choices.length)this.menu()}
hud(){ctx.save();ctx.setTransform(1,0,0,1,0,0);ctx.globalAlpha=1;ctx.globalCompositeOperation="source-over";ctx.shadowBlur=0;ctx.textAlign="left";ctx.textBaseline="alphabetic";
ctx.fillStyle="rgba(7,12,9,.94)";ctx.fillRect(104,282,432,74);ctx.strokeStyle="#647a55";ctx.lineWidth=1;ctx.strokeRect(104.5,282.5,431,73);
let hp=Math.max(0,Math.min(1,this.p.hp/this.p.maxHp)),xp=Math.max(0,Math.min(1,this.p.xp/this.p.need));
ctx.fillStyle="#261315";ctx.fillRect(120,292,176,14);ctx.fillStyle="#d94f50";ctx.fillRect(122,294,172*hp,10);ctx.strokeStyle="#efe9d4";ctx.strokeRect(120.5,292.5,175,13);
ctx.fillStyle="#142334";ctx.fillRect(120,311,176,9);ctx.fillStyle="#59a9e8";ctx.fillRect(122,313,172*xp,5);ctx.strokeStyle="#a9bdd0";ctx.strokeRect(120.5,311.5,175,8);
ctx.fillStyle="#fff";ctx.font="bold 8px sans-serif";ctx.fillText(`HP ${Math.ceil(this.p.hp)} / ${this.p.maxHp}`,126,302);ctx.font="9px sans-serif";ctx.fillText(`LV ${this.p.level}   XP ${Math.floor(this.p.xp)}/${this.p.need}   GOLD ${this.p.gold}`,120,338);
let xs=[310,354,398,442],ks=["q","w","e","r"],cd=[16,9,13,35],icons=[this.i.sq,this.i.sw,this.i.se,this.i.sr];
for(let j=0;j<4;j++){let s=this.p[ks[j]],x=xs[j];ctx.fillStyle="#101712";ctx.fillRect(x,306,42,42);ctx.drawImage(icons[j],x+3,309,36,36);
if(!s.open){ctx.fillStyle="rgba(0,0,0,.82)";ctx.fillRect(x,306,42,42)}else if(s.cd>0){let ratio=Math.max(0,Math.min(1,s.cd/cd[j]));ctx.fillStyle="rgba(0,0,0,.68)";ctx.fillRect(x,306,42,42*ratio);ctx.fillStyle="#fff";ctx.font="bold 10px sans-serif";ctx.textAlign="center";ctx.fillText(s.cd.toFixed(1),x+21,332)}
ctx.strokeStyle=s.open&&s.cd<=0?"#e3edc9":"#8b9980";ctx.strokeRect(x+.5,306.5,41,41);ctx.fillStyle="#fff";ctx.font="bold 9px sans-serif";ctx.textAlign="left";ctx.fillText(ks[j].toUpperCase(),x+3,316)}
ctx.restore()}
menu(){ctx.save();ctx.setTransform(1,0,0,1,0,0);ctx.globalAlpha=1;ctx.globalCompositeOperation="source-over";ctx.shadowBlur=0;ctx.textAlign="center";ctx.textBaseline="alphabetic";
ctx.fillStyle="rgba(2,5,4,.92)";ctx.fillRect(0,0,C.W,C.H);
ctx.fillStyle="#f3f2df";ctx.font="bold 22px sans-serif";ctx.fillText(`LEVEL ${this.p.level}`,C.W/2,68);
ctx.fillStyle="#b9cfa5";ctx.font="12px sans-serif";ctx.fillText("1 / 2 / 3 중 하나를 선택하세요",C.W/2,92);
let choices=this.p.choices.length?this.p.choices:[{n:"선택지 생성 오류"},{n:"다시 레벨업하세요"},{n:""}];
choices.slice(0,3).forEach((o,i)=>{let x=70+i*170,y=118,w=160,h=128;
ctx.fillStyle="#111c14";ctx.fillRect(x,y,w,h);ctx.strokeStyle="#a8c77f";ctx.lineWidth=2;ctx.strokeRect(x+1,y+1,w-2,h-2);
ctx.fillStyle="#eaf1d5";ctx.font="bold 24px sans-serif";ctx.fillText(String(i+1),x+w/2,y+32);
ctx.fillStyle="#ffffff";ctx.font="bold 13px sans-serif";ctx.fillText(o.n||"강화 선택",x+w/2,y+72);
ctx.fillStyle="#9eb58d";ctx.font="10px sans-serif";ctx.fillText("숫자 키를 눌러 선택",x+w/2,y+102)});
ctx.restore()}
loop=(t)=>{let dt=Math.min((t-this.last)/1000,.05);this.last=t;this.u(dt);this.draw();this.input.end();requestAnimationFrame(this.loop)}
start(){loading.classList.add("hidden");requestAnimationFrame(this.loop)}
}
const M={idle:"assets/player/idle.png",run:"assets/player/run.png",attack:"assets/player/attack.png",slime:"assets/enemies/slime.png",archer:"assets/enemies/archer.png",archerAttack:"assets/enemies/archer_attack.png",lancer:"assets/enemies/lancer.png",lancerAttack:"assets/enemies/lancer_attack.png",boss:"assets/enemies/middle_boss.png",bossAttack:"assets/enemies/boss_attack.png",arrow:"assets/projectiles/arrow.png",villager:"assets/npc/villager.png",oldman:"assets/npc/oldman.png",monk:"assets/npc/monk.png",hunter:"assets/npc/hunter.png",princess:"assets/npc/princess.png",grass:"assets/tiles/grass.png",plains:"assets/tiles/plains.png",circle:"assets/fx/circle.png",a1:"assets/fx/alpha_1.png",a2:"assets/fx/alpha_2.png",a3:"assets/fx/alpha_3.png",a4:"assets/fx/alpha_4.png",castle:"assets/buildings/castle.png",house1:"assets/buildings/house1.png",house2:"assets/buildings/house2.png",monastery:"assets/buildings/monastery.png",barracks:"assets/buildings/barracks.png",sq:"assets/skills/q.png",sw:"assets/skills/w.png",se:"assets/skills/e.png",sr:"assets/skills/r.png",med1:"assets/fx/meditate/meditate1.png",med2:"assets/fx/meditate/meditate2.png",med3:"assets/fx/meditate/meditate3.png"};
(async()=>{try{new Game(await new Loader(M).load()).start()}catch(e){console.error(e);loadingText.textContent=e.message}})();
